[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "16.20.2" # Versão LTS compatível com react-scripts
  NODE_OPTIONS = "--openssl-legacy-provider"